### ISSUE TITLE
Will this be signed?

### ISSUE THREAD

**Issue by aka-John99** [luser/crashme#2]
This is a useful diagnostic tool that will be used on Firefox Release.

Are there plans to ensure that this will be a signed addon even if not hosted on AMO ?
Related is: Bug [1162727](https://bugzilla.mozilla.org/show_bug.cgi?id=1162727) - ADB Helper, Valence, and Simulator extensions are not signed

**Comment by luser** [comment]
I honestly just haven't looked into it. I only really run Nightly so it's not likely to be a problem for me, but I agree that it's useful to have for release builds. I'll see if I can get it signed.

**Comment by aka-John99** [comment]
Support Mozilla KB now edited to recommend a (signed) alternative add-on
 [Crash Me Now! (Simple)](https://addons.mozilla.org/firefox/addon/crash-me-now-simple/)
for the benefit of those Troubleshooting Release issues.

**Comment by luser** [comment]
Yeah, that was what I wound up doing instead. :)
